function [X]=modmotor(Ts, xant, u)
Laa = 5.2888e-04;
J = 2.6104e-09;
Ra = 20;
B = 0;
Ki = 0.0102;
Km = 0.0605;
Va=u;
h=1e-7;
omega= xant(1);
wp = xant(2);
theta = xant(3);
for ii=1:Ts/h
wpp =(-wp*(Ra*J+Laa*B)-omega*(Ra*B+Ki*Km)+Va*Ki)/(J*Laa);
wp = wp+h*wpp;
omega = omega + h*wp;
theta_p = omega;
theta = theta + h*theta_p;
end
X=[omega,wp,theta];
